name: sigrid-publish
on:
  push:
    branches:
      - "master"
jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Special case: We use Sigrid CI on itself, so if we want its own code to be analyzed we need a copy"
        run: "cp -r sigridci src"
      - name: "Run Sigrid CI" 
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
        run: "./sigridci/sigridci.py --customer opensource --system ci-training --source . --targetquality 4.0 --publish" 
      - name: "Save Sigrid CI results"
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v2
        with:
          path: "sigrid-ci-output/**"
          retention-days: 7
          if-no-files-found: ignore
