name: sigrid-publish
on:
  push:
    branches:
      - "master"
jobs:
  sigridci:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@v1.2
        with:
          customer: opensource
          system: ci-training
          targetquality: 3.5
          publish: true
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
          